### ISSUE TITLE
ProjectName

### ISSUE THREAD

**Issue by dweorh** [phofman/vs-plugin#33]
Hey,
It would be cool if default project name be the same as the import project folder name or, even better, a projectDescription/name from .project. 

When you have few projects to import it's easy to forget to change default project name and then I have to import project once again with correct name.

thanks,

btw. nice plugin, momentics is cool but it's 'as-is' ;)

**Comment by phofman** [comment]
Additionally it could also scan for library references and let to input new preprocessor defines.

**Comment by phofman** [comment]
Sorry, it took so long. But finally project name/defines/referenced-libraries are read from original Momentics project and presented on UI. It's already pushed on 'develop' branch and will appear with the next release.
