### ISSUE TITLE
Project import

### ISSUE THREAD

**Issue by dweorh** [phofman/vs-plugin#34]
Hey again,

One more thing concerning project import.
I'm using svn, git as well, but svn 'produce' a lot of folders and subfolders with billions of files inside.

What do you think to add kind of 'filter' to remove such dummy files from import files list?

I know that I can uncheck them but filter like 'exclude folders: .svn' or 'exclude files: _.git_' would be a cool feature.

Thanks

**Comment by phofman** [comment]
Sorry, it took so long. Now you can check/uncheck/remove files from the list, simply by right-clicking them and using context menu.

It's already pushed on 'develop' branch and will appear in the next release.
