### ISSUE TITLE
Visual Studio 2013 Prof. not recognizing plugin

### ISSUE THREAD

**Issue by splatterb0y** [phofman/vs-plugin#39]
I have Momentics and Visual Studio 2013 Update 4 Prof. installed on my drive H:, running Windows 8.1.

I can't find any hints that Visual Studio is recognizing the plugin after I installed it.

**Comment by phofman** [comment]
Don't you see the _BlackBerry_ top-menu next to _Tools_? Nor, the plugin listed in _Tools->Extensions_ and Updates like on an image below?

New projects might be hidden under 'Other Languages' if your Visual Studio is configured for C# developer.

The installation path on H drive should be irrelevant, as VSIX packages are extracted into correct location by Visual Studio itself.

![newprojects](https://cloud.githubusercontent.com/assets/475630/6731730/35114d2a-ce47-11e4-8cb8-8fca315c8818.jpg)

![extensions](https://cloud.githubusercontent.com/assets/475630/6731657/b3efab6a-ce46-11e4-87e4-65b7e297579b.jpg)

**Comment by splatterb0y** [comment]
There is no additional menu item, the plugin is not shown unter "Extensions and Updates" and the templates are not there too. I'm using a 64-Bit Version of Windows by the way. 

I scanned my hard drives C and H for a VSIX file but there is none. After tinkering around with that I decided to build the plugin from source and install it with the batch file, no success too. 

Thats the second PC I try to install this but no luck sadly. :(

**Comment by phofman** [comment]
Hmm...
I am using two machines Win8.1-x64 and VS2012/VS2013 for development without any problems.
You can always try to download it from [here](https://visualstudiogallery.msdn.microsoft.com/9a03ae7e-b786-41a7-a63b-dc0d9fe818d2) and retry.

VSIX is just an installable package (zip). If you use the build script the VSIX is expected at __BuildResults/VS2013/_ folder. When build directly using VS, it will be placed under _src_vs2013/Package/bin/Debug_. When you install it, it gets automatically extracted and placed under:

`<user_home_folder>\AppData\Local\Microsoft\VisualStudio\<vs_version>\Extensions\<random_name>\`

Try to search for 'BlackBerry.Package.dll' there.

**Comment by splatterb0y** [comment]
I figured it out. Visual Studio 2013 [https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs.aspx] and Visual Studio 2013 SDK [http://www.microsoft.com/en-us/download/details.aspx?id=40758] are indeed two different things, that was the point I wasn't aware off. I have both installed now and the plugin is recognised. 

Thanks for your time and support!
