### ISSUE TITLE
Visual Studio 2015

### ISSUE THREAD

**Issue by Mike-Goncalves** [phofman/vs-plugin#45]
Hello,

Is there any plan to release this plugin for VS2015?

Best Regards

**Comment by phofman** [comment]
Yes, there is such a plan. I will finish it up most probably within the next 2 weeks.

**Comment by phofman** [comment]
OK, pretty much alpha version of VS2015 integration is completed.
Would you be interested in testing the package? ... while I progress with fixing known issue (of non-working C++11) and extending the build scripts to add new artifacts.

**Comment by Mike-Goncalves** [comment]
Yes I'd like very much to test it. I'l be sure to report any bugs I can find here!

**Comment by phofman** [comment]
OK. [Here](/phofman/vs-plugin/releases/tag/v3.6.0-alpha) is the vsix to load and install. Let me know, what you have found. Thanks.

**Comment by phofman** [comment]
VS2015 is officially supported. Try to install the extension from here:
https://visualstudiogallery.msdn.microsoft.com/2b21e9d1-a54b-4d58-878f-2d53604e85b1
