### ISSUE TITLE
Visual Studio "Exclude from Build" has not effect on BlackBerry Project

### ISSUE THREAD

**Issue by HongkunWang** [phofman/vs-plugin#47]
Visual Studio "Exclude from Build" has no effect on BlackBerry Project, the work around is remove those unwanted source code from project, but is not as convenient as use "Exclude from Build".

**Comment by phofman** [comment]
Yes, confirmed.
Currently all source-code files from the solution are used to generate output without any filtering. I will apply the exclution.

**Comment by phofman** [comment]
It's been fixed now and this settings is respected correctly. You will see it in the next public release.
