### ISSUE TITLE
Prefix header inclusion is not available

### ISSUE THREAD

**Issue by HongkunWang** [phofman/vs-plugin#50]
Most of IDEs, including VS, has a C/C++ option in "Advanced" part, called "force include header" or "prefix header", means every headers will has specified prefixed header included at the top. This is biggest missing functions in QNX compiler. In GCC, the option is "-include".

**Comment by phofman** [comment]
When in project properties, navigate to `C/C++` -> `Command Line` and there is a field `Additional Options`. You can specify there anything, that will be appended to the command passed to compiler.
Let me know, if this helps.

**Comment by HongkunWang** [comment]
Hi,
It will not help. The standard gcc option “-include” is not supported by QCC, so this problem might be out of your control.
Hongkun

**Comment by phofman** [comment]
Closing as I can't fix it.

**Comment by HongkunWang** [comment]
Hi Pawel,

I got a “Error loading application package: Permission denied” error when I tried to deploy my BalackBerry application to the USB-connected device, see the log below.

What I have:
- Window 10 official edition (Build 10240)
- Visual Studio 2015 official edition
- BB plugin for VS 2015 V3.6.3

Hongkun

---

8> Preparing BAR for Device

8> GameEngineDemo.BlackBerry.vcxproj ->

8> Info: Sending request: GET_FILE

8> Info: Action: Get File

8> Info: Package com.omnigsoft.GameEngineDemo.testDev_eEngineDemo7ef260da

8> Info: Asset Path ../../../../apps/com.omnigsoft.GameEngineDemo.testDev_eEngineDemo7ef260da/META-INF/MANIFEST.MF

8> Info: Sending File: 31848

8> Info: File saved: targetManifest.mf

8> Info: Sending request: PUT_FILE

8> Info: Action: Put File

8> Info: File size: 31848

8> Info: Package com.omnigsoft.GameEngineDemo.testDev_eEngineDemo7ef260da

8> Info: Asset Path ../../../../apps/com.omnigsoft.GameEngineDemo.testDev_eEngineDemo7ef260da/META-INF/MANIFEST.MF

8> result::success

8> Info: Sending request: LAUNCH

8> Info: Action: Launch

8> Info: Launching com.omnigsoft.GameEngineDemo.testDev_eEngineDemo7ef260da...

8>BBDeploy : error : Error loading application package: Permission denied

8>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\BlackBerry\Microsoft.Cpp.BlackBerry.Packager.targets(372,5): error MSB6006: "C:\bbndk\host_10_3_0_2702\win32\x86\usr\bin\blackberry-deploy.bat" exited with code 2.

========== Build: 1 succeeded, 0 failed, 6 up-to-date, 0 skipped ==========

========== Deploy: 0 succeeded, 1 failed, 6 skipped ==========

**Comment by HongkunWang** [comment]
Sorry, please ignore the previous report, it was a fake alarm, the problem is caused by an expired debug token.
Hongkun

From: hongkun 
Sent: Tuesday, August 4, 2015 11:51 AM
To: phofman/vs-plugin 
Subject: Re: Error loading application package: Permission denied

Hi Pawel,

I got a “Error loading application package: Permission denied” error when I tried to deploy my BalackBerry application to the USB-connected device, see the log below.

What I have:
- Window 10 official edition (Build 10240)
- Visual Studio 2015 official edition
- BB plugin for VS 2015 V3.6.3

Hongkun

---

8> Preparing BAR for Device

8> GameEngineDemo.BlackBerry.vcxproj ->

8> Info: Sending request: GET_FILE

8> Info: Action: Get File

8> Info: Package com.omnigsoft.GameEngineDemo.testDev_eEngineDemo7ef260da

8> Info: Asset Path ../../../../apps/com.omnigsoft.GameEngineDemo.testDev_eEngineDemo7ef260da/META-INF/MANIFEST.MF

8> Info: Sending File: 31848

8> Info: File saved: targetManifest.mf

8> Info: Sending request: PUT_FILE

8> Info: Action: Put File

8> Info: File size: 31848

8> Info: Package com.omnigsoft.GameEngineDemo.testDev_eEngineDemo7ef260da

8> Info: Asset Path ../../../../apps/com.omnigsoft.GameEngineDemo.testDev_eEngineDemo7ef260da/META-INF/MANIFEST.MF

8> result::success

8> Info: Sending request: LAUNCH

8> Info: Action: Launch

8> Info: Launching com.omnigsoft.GameEngineDemo.testDev_eEngineDemo7ef260da...

8>BBDeploy : error : Error loading application package: Permission denied

8>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\BlackBerry\Microsoft.Cpp.BlackBerry.Packager.targets(372,5): error MSB6006: "C:\bbndk\host_10_3_0_2702\win32\x86\usr\bin\blackberry-deploy.bat" exited with code 2.

========== Build: 1 succeeded, 0 failed, 6 up-to-date, 0 skipped ==========

========== Deploy: 0 succeeded, 1 failed, 6 skipped ==========

**Comment by phofman** [comment]
Right, you will get similar error, when you install 'release' and signed version and then try the 'debug' build.

BTW. Could you please open another issue and don't reuse existing one :) ?
