### ISSUE TITLE
How can I get it working on Linux?

### ISSUE THREAD

**Issue by qnxdev** [phofman/vs-plugin#55]
Is it possible to make this available on extensions market?
A wave of developers are now developing apps on BB10 in 2020.

**Comment by phofman** [comment]
Hello there!

AFAIK it is available on the marketplace [here](https://marketplace.visualstudio.com/items?itemName=CodeTitans.BlackBerryNativePluginforVisualStudio2015) for Visual Studio 2015, 2013 and 2012.

But I doubt it will ever work on Linux out of the box, as Visual Studio doesn’t support it.
